accelerator: auto
attention_values:
- 4
- 5
audio_clip_length: 3.0
audio_length: 59049
audio_repr: raw
audio_sample_rate: 44100
batch_size: 8
checkpoint_path: ''
clamp_value: 20
clap_pretrained: ''
clap_proj_hidden_dim: 256
cv_held_out_id: -1
cv_mode: within
dataset: preprocessing_eegmusic
dataset_dir: ../dataset
detach_z_c: 0
devices: 1
dim_reduction: 1
eeg_length: 768
eeg_normalization: MetaAI
eeg_sample_rate: 256
evaluation_length: null
key: all
learning_rate: 0.003
log_dir: ../results
loss_function: clip_loss
max_amplitude: 0.015
max_epochs: 1000
min_amplitude: 0.001
mode: null
openmiir_augmentation: no_augmentation
optimizer: Adam
resume_checkpoint_path: ''
sample_rate: 22050
seed: 42
shifting_time: 0
shuffle_test_mode: none
song_id: null
split_seed: 42
start_position: 0
stride: 256
subject_id: null
supervised: 1
temperature: 0.5
test_breakdown: 1
test_data_length: 768
test_dataset: preprocessing_eegmusic_test
test_stride: 256
test_window_size: 768
train_test_splitting: none
training_date: raw_within_scratch
whole_audio_length: 15.0
window_size: 1280
workers: 6
